---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forge-mi-ingress-base-static
spec:
  tls:
    - hosts:
        - demo-1404-arnaud.apps.ocp4-7.infocepo.com
  rules:
    - host: demo-1404-arnaud.apps.ocp4-7.infocepo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dso-demo-static
                port:
                  number: 8080


